version: '3.8'

services:
  app:
    image: ghcr.io/nguard-security/nguard_security_api_new:latest
    ports:
      - 4000:4000
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    labels:
      - 'name=redis'
      - 'mode=standalone'
    restart: always
